### ISSUE TITLE
Add support for other OpenAI models (or at least "gpt-4o-mini")

### ISSUE THREAD

**Issue by waldenn** [aotakeda/learn-thing#11]
I tried to change the model to "gpt-4o-mini' manually, as it is quite a bit better than the "gpt-3.5-turbo" model, but that does not work yet unfortunately.

BTW: Also are you planning to make the tree-depth configurable or expandable? I think that would add a lot of value to the user experience.  Thanks for this project, looking forward to see how this develops.

**Comment by aotakeda** [comment]
newer OpenAI models should be working with the last update

and yes! I plan to add that feature soon!

**Comment by waldenn** [comment]
Thanks!
